### ISSUE TITLE
Experiment with making a PDF in Dart (Flutter)

### ISSUE THREAD

**Issue by holtzmak** [holtzmak/Humane-Transport#81]
Using the project framework set up in #56 , experiment with the following items:
* Make a PDF out of code objects using Dart
* Make a PDF out of code objects with images using Dart

You should use an existing library out there: document what kind of options it provides use with (for example, images, formatting the document, what about have a template PDF that's filled out using code objects for the ATR?)

Any code you write to do the above can be merged into the codebase - we'll be able to overwrite/copy/etc. when we go to create the final GUI windows/widgets. You may want to keep a list of references that helped you: for example, Flutter cookbook pages - decide if we should have a dedicated wiki page for Flutter cookbook items.

**Comment by mansiPaTeLL** [comment]
- [x] Find the useful library 
- [x] Make a PDF out of code objects using Dart
- [x] Make a PDF out of code objects with images using Dart

Found the useful library: 
https://pub.dev/packages/pdf
https://github.com/DavBfr/dart_pdf
https://medium.com/@kmerandi25/pdf-creation-with-flutter-bac7e2753b89
https://help.syncfusion.com/flutter/pdf/working-with-images

**Comment by mansiPaTeLL** [comment]
@holtzmak @MummenRider I have created the branch for Pdf file creation. In the code, I have just tested the manually entered data. Instead of those manually entered text, we will be calling API and fetching the data and building the pDF and formatting the PDF. 

I haven't also found the library for converting image or adding an image into the pdf file. You can see those useful library in the comment section above. Thanks.
